-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_0_ap_vld : OUT STD_LOGIC;
    layer11_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_1_ap_vld : OUT STD_LOGIC;
    layer11_out_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_2_ap_vld : OUT STD_LOGIC;
    layer11_out_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_3_ap_vld : OUT STD_LOGIC;
    layer11_out_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_4_ap_vld : OUT STD_LOGIC;
    layer11_out_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_5_ap_vld : OUT STD_LOGIC;
    layer11_out_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_6_ap_vld : OUT STD_LOGIC;
    layer11_out_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_7_ap_vld : OUT STD_LOGIC;
    layer11_out_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_8_ap_vld : OUT STD_LOGIC;
    layer11_out_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer11_out_9_ap_vld : OUT STD_LOGIC );
end;


architecture behav of myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exp_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q3 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q4 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q5 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address6 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q6 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address7 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q7 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address8 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q8 : STD_LOGIC_VECTOR (10 downto 0);
    signal exp_table_address9 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table_q9 : STD_LOGIC_VECTOR (10 downto 0);
    signal invert_table_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_reg_1181 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_2_reg_1186 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_1191 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_reg_1196 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_reg_1201 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_reg_1206 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_reg_1211 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_reg_1216 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_5_reg_1221 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_reg_1226 : STD_LOGIC_VECTOR (9 downto 0);
    signal a_fu_772_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_reg_1281 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_fu_784_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_reg_1286 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_2_fu_796_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_2_reg_1291 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_2_fu_808_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_2_reg_1296 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_4_fu_820_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_4_reg_1301 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_3_fu_832_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_3_reg_1306 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_5_fu_844_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_5_reg_1311 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_4_fu_856_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_4_reg_1316 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_6_fu_868_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal a_6_reg_1321 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_6_fu_880_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal b_6_reg_1326 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln258_fu_732_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln258_1_fu_736_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_2_fu_740_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_3_fu_744_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_4_fu_748_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_5_fu_752_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_6_fu_756_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_7_fu_760_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_8_fu_764_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln258_9_fu_768_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln267_fu_972_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal layer11_out_0_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal layer11_out_1_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_2_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_3_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_4_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_5_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_6_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_7_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_8_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal layer11_out_9_preg : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal exp_table_ce9_local : STD_LOGIC;
    signal exp_table_ce8_local : STD_LOGIC;
    signal exp_table_ce7_local : STD_LOGIC;
    signal exp_table_ce6_local : STD_LOGIC;
    signal exp_table_ce5_local : STD_LOGIC;
    signal exp_table_ce4_local : STD_LOGIC;
    signal exp_table_ce3_local : STD_LOGIC;
    signal exp_table_ce2_local : STD_LOGIC;
    signal exp_table_ce1_local : STD_LOGIC;
    signal exp_table_ce0_local : STD_LOGIC;
    signal invert_table_ce0_local : STD_LOGIC;
    signal icmp_ln66_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_fu_356_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_1_fu_376_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_2_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_4_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_3_fu_416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_4_fu_436_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_5_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_5_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln66_2_fu_396_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln66_5_fu_456_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_6_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_6_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_7_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_7_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal a_1_fu_476_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal b_1_fu_496_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_8_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_8_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln66_fu_516_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln66_1_fu_520_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln66_8_fu_524_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_fu_532_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_1_fu_542_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_2_fu_552_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_3_fu_562_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_4_fu_572_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_5_fu_582_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_6_fu_592_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_7_fu_602_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_8_fu_612_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln248_9_fu_622_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_fu_536_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_10_fu_546_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_11_fu_556_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_12_fu_566_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_13_fu_576_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_14_fu_586_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_15_fu_596_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_16_fu_606_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_17_fu_616_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal d_xi_xmax_18_fu_626_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln141_fu_780_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_2_fu_804_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_fu_892_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_1_fu_792_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal a_7_fu_898_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_1_fu_904_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln141_3_fu_816_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln141_5_fu_840_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_6_fu_852_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_3_fu_914_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln141_4_fu_828_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_4_fu_920_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_3_fu_926_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln51_2_fu_908_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal b_7_fu_930_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln51_2_fu_936_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln141_7_fu_864_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln141_8_fu_876_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_fu_888_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln51_7_fu_946_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_4_fu_952_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_6_fu_940_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln51_8_fu_956_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln_fu_962_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln270_fu_984_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln270_fu_977_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_fu_984_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_fu_984_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_1_fu_1004_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_1_fu_1004_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_1_fu_1004_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_2_fu_1024_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_2_fu_1024_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_2_fu_1024_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_3_fu_1044_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_3_fu_1044_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_3_fu_1044_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_4_fu_1064_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_4_fu_1064_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_4_fu_1064_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_5_fu_1084_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_5_fu_1084_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_5_fu_1084_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_6_fu_1104_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_6_fu_1104_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_6_fu_1104_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_7_fu_1124_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_7_fu_1124_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_7_fu_1124_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_8_fu_1144_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_8_fu_1144_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_8_fu_1144_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_9_fu_1164_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln270_9_fu_1164_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln270_9_fu_1164_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul_ln270_1_fu_1004_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_2_fu_1024_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_3_fu_1044_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_4_fu_1064_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_5_fu_1084_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_6_fu_1104_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_7_fu_1124_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_8_fu_1144_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_9_fu_1164_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln270_fu_984_p10 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_18s_15ns_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_exp_table_ROM_g8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address6 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address7 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address8 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce8 : IN STD_LOGIC;
        q8 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address9 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce9 : IN STD_LOGIC;
        q9 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_invert_table_Rhbi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_exp_table_ROM_g8j
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table_address0,
        ce0 => exp_table_ce0_local,
        q0 => exp_table_q0,
        address1 => exp_table_address1,
        ce1 => exp_table_ce1_local,
        q1 => exp_table_q1,
        address2 => exp_table_address2,
        ce2 => exp_table_ce2_local,
        q2 => exp_table_q2,
        address3 => exp_table_address3,
        ce3 => exp_table_ce3_local,
        q3 => exp_table_q3,
        address4 => exp_table_address4,
        ce4 => exp_table_ce4_local,
        q4 => exp_table_q4,
        address5 => exp_table_address5,
        ce5 => exp_table_ce5_local,
        q5 => exp_table_q5,
        address6 => exp_table_address6,
        ce6 => exp_table_ce6_local,
        q6 => exp_table_q6,
        address7 => exp_table_address7,
        ce7 => exp_table_ce7_local,
        q7 => exp_table_q7,
        address8 => exp_table_address8,
        ce8 => exp_table_ce8_local,
        q8 => exp_table_q8,
        address9 => exp_table_address9,
        ce9 => exp_table_ce9_local,
        q9 => exp_table_q9);

    invert_table_U : component myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_invert_table_Rhbi
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table_address0,
        ce0 => invert_table_ce0_local,
        q0 => invert_table_q0);

    mul_18s_15ns_30_1_1_U11834 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_fu_984_p0,
        din1 => mul_ln270_fu_984_p1,
        dout => mul_ln270_fu_984_p2);

    mul_18s_15ns_30_1_1_U11835 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_1_fu_1004_p0,
        din1 => mul_ln270_1_fu_1004_p1,
        dout => mul_ln270_1_fu_1004_p2);

    mul_18s_15ns_30_1_1_U11836 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_2_fu_1024_p0,
        din1 => mul_ln270_2_fu_1024_p1,
        dout => mul_ln270_2_fu_1024_p2);

    mul_18s_15ns_30_1_1_U11837 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_3_fu_1044_p0,
        din1 => mul_ln270_3_fu_1044_p1,
        dout => mul_ln270_3_fu_1044_p2);

    mul_18s_15ns_30_1_1_U11838 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_4_fu_1064_p0,
        din1 => mul_ln270_4_fu_1064_p1,
        dout => mul_ln270_4_fu_1064_p2);

    mul_18s_15ns_30_1_1_U11839 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_5_fu_1084_p0,
        din1 => mul_ln270_5_fu_1084_p1,
        dout => mul_ln270_5_fu_1084_p2);

    mul_18s_15ns_30_1_1_U11840 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_6_fu_1104_p0,
        din1 => mul_ln270_6_fu_1104_p1,
        dout => mul_ln270_6_fu_1104_p2);

    mul_18s_15ns_30_1_1_U11841 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_7_fu_1124_p0,
        din1 => mul_ln270_7_fu_1124_p1,
        dout => mul_ln270_7_fu_1124_p2);

    mul_18s_15ns_30_1_1_U11842 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_8_fu_1144_p0,
        din1 => mul_ln270_8_fu_1144_p1,
        dout => mul_ln270_8_fu_1144_p2);

    mul_18s_15ns_30_1_1_U11843 : component myproject_mul_18s_15ns_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 15,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln270_9_fu_1164_p0,
        din1 => mul_ln270_9_fu_1164_p1,
        dout => mul_ln270_9_fu_1164_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    layer11_out_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_0_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_0_preg <= mul_ln270_fu_984_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_1_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_1_preg <= mul_ln270_1_fu_1004_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_2_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_2_preg <= mul_ln270_2_fu_1024_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_3_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_3_preg <= mul_ln270_3_fu_1044_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_4_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_4_preg <= mul_ln270_4_fu_1064_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_5_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_5_preg <= mul_ln270_5_fu_1084_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_6_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_6_preg <= mul_ln270_6_fu_1104_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_7_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_7_preg <= mul_ln270_7_fu_1124_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_8_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_8_preg <= mul_ln270_8_fu_1144_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;


    layer11_out_9_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                layer11_out_9_preg <= ap_const_lv16_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    layer11_out_9_preg <= mul_ln270_9_fu_1164_p2(29 downto 14);
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                    a_2_reg_1291(14 downto 4) <= a_2_fu_796_p3(14 downto 4);
                    a_4_reg_1301(14 downto 4) <= a_4_fu_820_p3(14 downto 4);
                    a_5_reg_1311(14 downto 4) <= a_5_fu_844_p3(14 downto 4);
                    a_6_reg_1321(14 downto 4) <= a_6_fu_868_p3(14 downto 4);
                    a_reg_1281(14 downto 4) <= a_fu_772_p3(14 downto 4);
                    b_2_reg_1296(14 downto 4) <= b_2_fu_808_p3(14 downto 4);
                    b_3_reg_1306(14 downto 4) <= b_3_fu_832_p3(14 downto 4);
                    b_4_reg_1316(14 downto 4) <= b_4_fu_856_p3(14 downto 4);
                    b_6_reg_1326(14 downto 4) <= b_6_fu_880_p3(14 downto 4);
                    b_reg_1286(14 downto 4) <= b_fu_784_p3(14 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_1_reg_1211 <= d_xi_xmax_15_fu_596_p2(14 downto 5);
                tmp_2_reg_1186 <= d_xi_xmax_10_fu_546_p2(14 downto 5);
                tmp_3_reg_1216 <= d_xi_xmax_16_fu_606_p2(14 downto 5);
                tmp_4_reg_1191 <= d_xi_xmax_11_fu_556_p2(14 downto 5);
                tmp_5_reg_1221 <= d_xi_xmax_17_fu_616_p2(14 downto 5);
                tmp_6_reg_1196 <= d_xi_xmax_12_fu_566_p2(14 downto 5);
                tmp_7_reg_1226 <= d_xi_xmax_18_fu_626_p2(14 downto 5);
                tmp_8_reg_1201 <= d_xi_xmax_13_fu_576_p2(14 downto 5);
                tmp_reg_1181 <= d_xi_xmax_fu_536_p2(14 downto 5);
                tmp_s_reg_1206 <= d_xi_xmax_14_fu_586_p2(14 downto 5);
            end if;
        end if;
    end process;
    a_reg_1281(3 downto 0) <= "0000";
    b_reg_1286(3 downto 0) <= "0000";
    a_2_reg_1291(3 downto 0) <= "0000";
    b_2_reg_1296(3 downto 0) <= "0000";
    a_4_reg_1301(3 downto 0) <= "0000";
    b_3_reg_1306(3 downto 0) <= "0000";
    a_5_reg_1311(3 downto 0) <= "0000";
    b_4_reg_1316(3 downto 0) <= "0000";
    a_6_reg_1321(3 downto 0) <= "0000";
    b_6_reg_1326(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    a_1_fu_476_p3 <= 
        select_ln66_2_fu_396_p3 when (xor_ln66_6_fu_470_p2(0) = '1') else 
        select_ln66_5_fu_456_p3;
    a_2_fu_796_p3 <= (exp_table_q7 & ap_const_lv4_0);
    a_4_fu_820_p3 <= (exp_table_q5 & ap_const_lv4_0);
    a_5_fu_844_p3 <= (exp_table_q3 & ap_const_lv4_0);
    a_6_fu_868_p3 <= (exp_table_q1 & ap_const_lv4_0);
    a_7_fu_898_p2 <= std_logic_vector(unsigned(add_ln51_fu_892_p2) + unsigned(zext_ln141_1_fu_792_p1));
    a_fu_772_p3 <= (exp_table_q9 & ap_const_lv4_0);
    add_ln51_2_fu_908_p2 <= std_logic_vector(unsigned(zext_ln51_1_fu_904_p1) + unsigned(zext_ln141_3_fu_816_p1));
    add_ln51_3_fu_914_p2 <= std_logic_vector(unsigned(zext_ln141_5_fu_840_p1) + unsigned(zext_ln141_6_fu_852_p1));
    add_ln51_4_fu_920_p2 <= std_logic_vector(unsigned(add_ln51_3_fu_914_p2) + unsigned(zext_ln141_4_fu_828_p1));
    add_ln51_6_fu_940_p2 <= std_logic_vector(unsigned(zext_ln51_2_fu_936_p1) + unsigned(zext_ln141_7_fu_864_p1));
    add_ln51_7_fu_946_p2 <= std_logic_vector(unsigned(zext_ln141_8_fu_876_p1) + unsigned(zext_ln51_fu_888_p1));
    add_ln51_8_fu_956_p2 <= std_logic_vector(unsigned(zext_ln51_4_fu_952_p1) + unsigned(add_ln51_6_fu_940_p2));
    add_ln51_fu_892_p2 <= std_logic_vector(unsigned(zext_ln141_fu_780_p1) + unsigned(zext_ln141_2_fu_804_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter3, ap_done_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to2)
    begin
        if ((ap_idle_pp0_0to2 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    b_1_fu_496_p3 <= 
        p_read8 when (xor_ln66_7_fu_490_p2(0) = '1') else 
        p_read9;
    b_2_fu_808_p3 <= (exp_table_q6 & ap_const_lv4_0);
    b_3_fu_832_p3 <= (exp_table_q4 & ap_const_lv4_0);
    b_4_fu_856_p3 <= (exp_table_q2 & ap_const_lv4_0);
    b_6_fu_880_p3 <= (exp_table_q0 & ap_const_lv4_0);
    b_7_fu_930_p2 <= std_logic_vector(unsigned(zext_ln51_3_fu_926_p1) + unsigned(add_ln51_2_fu_908_p2));
    b_fu_784_p3 <= (exp_table_q8 & ap_const_lv4_0);
    d_xi_xmax_10_fu_546_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_1_fu_542_p1));
    d_xi_xmax_11_fu_556_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_2_fu_552_p1));
    d_xi_xmax_12_fu_566_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_3_fu_562_p1));
    d_xi_xmax_13_fu_576_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_4_fu_572_p1));
    d_xi_xmax_14_fu_586_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_5_fu_582_p1));
    d_xi_xmax_15_fu_596_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_6_fu_592_p1));
    d_xi_xmax_16_fu_606_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_7_fu_602_p1));
    d_xi_xmax_17_fu_616_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_8_fu_612_p1));
    d_xi_xmax_18_fu_626_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_9_fu_622_p1));
    d_xi_xmax_fu_536_p2 <= std_logic_vector(unsigned(select_ln66_8_fu_524_p3) - unsigned(trunc_ln248_fu_532_p1));
    exp_table_address0 <= zext_ln258_9_fu_768_p1(10 - 1 downto 0);
    exp_table_address1 <= zext_ln258_8_fu_764_p1(10 - 1 downto 0);
    exp_table_address2 <= zext_ln258_7_fu_760_p1(10 - 1 downto 0);
    exp_table_address3 <= zext_ln258_6_fu_756_p1(10 - 1 downto 0);
    exp_table_address4 <= zext_ln258_5_fu_752_p1(10 - 1 downto 0);
    exp_table_address5 <= zext_ln258_4_fu_748_p1(10 - 1 downto 0);
    exp_table_address6 <= zext_ln258_3_fu_744_p1(10 - 1 downto 0);
    exp_table_address7 <= zext_ln258_2_fu_740_p1(10 - 1 downto 0);
    exp_table_address8 <= zext_ln258_1_fu_736_p1(10 - 1 downto 0);
    exp_table_address9 <= zext_ln258_fu_732_p1(10 - 1 downto 0);

    exp_table_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce0_local <= ap_const_logic_1;
        else 
            exp_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce1_local <= ap_const_logic_1;
        else 
            exp_table_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce2_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce2_local <= ap_const_logic_1;
        else 
            exp_table_ce2_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce3_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce3_local <= ap_const_logic_1;
        else 
            exp_table_ce3_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce4_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce4_local <= ap_const_logic_1;
        else 
            exp_table_ce4_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce5_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce5_local <= ap_const_logic_1;
        else 
            exp_table_ce5_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce6_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce6_local <= ap_const_logic_1;
        else 
            exp_table_ce6_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce7_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce7_local <= ap_const_logic_1;
        else 
            exp_table_ce7_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce8_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce8_local <= ap_const_logic_1;
        else 
            exp_table_ce8_local <= ap_const_logic_0;
        end if; 
    end process;


    exp_table_ce9_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table_ce9_local <= ap_const_logic_1;
        else 
            exp_table_ce9_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln66_1_fu_364_p2 <= "1" when (signed(p_read2) < signed(p_read3)) else "0";
    icmp_ln66_2_fu_384_p2 <= "1" when (signed(select_ln66_fu_356_p3) < signed(select_ln66_1_fu_376_p3)) else "0";
    icmp_ln66_3_fu_404_p2 <= "1" when (signed(p_read4) < signed(p_read5)) else "0";
    icmp_ln66_4_fu_424_p2 <= "1" when (signed(p_read6) < signed(p_read7)) else "0";
    icmp_ln66_5_fu_444_p2 <= "1" when (signed(select_ln66_3_fu_416_p3) < signed(select_ln66_4_fu_436_p3)) else "0";
    icmp_ln66_6_fu_464_p2 <= "1" when (signed(select_ln66_2_fu_396_p3) < signed(select_ln66_5_fu_456_p3)) else "0";
    icmp_ln66_7_fu_484_p2 <= "1" when (signed(p_read8) < signed(p_read9)) else "0";
    icmp_ln66_8_fu_504_p2 <= "1" when (signed(a_1_fu_476_p3) < signed(b_1_fu_496_p3)) else "0";
    icmp_ln66_fu_344_p2 <= "1" when (signed(p_read) < signed(p_read1)) else "0";
    invert_table_address0 <= zext_ln267_fu_972_p1(10 - 1 downto 0);

    invert_table_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            invert_table_ce0_local <= ap_const_logic_1;
        else 
            invert_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_0_assign_proc : process(ap_enable_reg_pp0_iter3, layer11_out_0_preg, ap_block_pp0_stage0_01001, mul_ln270_fu_984_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_0 <= mul_ln270_fu_984_p2(29 downto 14);
        else 
            layer11_out_0 <= layer11_out_0_preg;
        end if; 
    end process;


    layer11_out_0_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_0_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_0_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_1_preg, mul_ln270_1_fu_1004_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_1 <= mul_ln270_1_fu_1004_p2(29 downto 14);
        else 
            layer11_out_1 <= layer11_out_1_preg;
        end if; 
    end process;


    layer11_out_1_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_1_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_2_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_2_preg, mul_ln270_2_fu_1024_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_2 <= mul_ln270_2_fu_1024_p2(29 downto 14);
        else 
            layer11_out_2 <= layer11_out_2_preg;
        end if; 
    end process;


    layer11_out_2_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_2_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_3_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_3_preg, mul_ln270_3_fu_1044_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_3 <= mul_ln270_3_fu_1044_p2(29 downto 14);
        else 
            layer11_out_3 <= layer11_out_3_preg;
        end if; 
    end process;


    layer11_out_3_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_3_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_4_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_4_preg, mul_ln270_4_fu_1064_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_4 <= mul_ln270_4_fu_1064_p2(29 downto 14);
        else 
            layer11_out_4 <= layer11_out_4_preg;
        end if; 
    end process;


    layer11_out_4_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_4_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_5_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_5_preg, mul_ln270_5_fu_1084_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_5 <= mul_ln270_5_fu_1084_p2(29 downto 14);
        else 
            layer11_out_5 <= layer11_out_5_preg;
        end if; 
    end process;


    layer11_out_5_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_5_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_6_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_6_preg, mul_ln270_6_fu_1104_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_6 <= mul_ln270_6_fu_1104_p2(29 downto 14);
        else 
            layer11_out_6 <= layer11_out_6_preg;
        end if; 
    end process;


    layer11_out_6_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_6_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_7_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_7_preg, mul_ln270_7_fu_1124_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_7 <= mul_ln270_7_fu_1124_p2(29 downto 14);
        else 
            layer11_out_7 <= layer11_out_7_preg;
        end if; 
    end process;


    layer11_out_7_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_7_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_8_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_8_preg, mul_ln270_8_fu_1144_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_8 <= mul_ln270_8_fu_1144_p2(29 downto 14);
        else 
            layer11_out_8 <= layer11_out_8_preg;
        end if; 
    end process;


    layer11_out_8_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_8_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    layer11_out_9_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_01001, layer11_out_9_preg, mul_ln270_9_fu_1164_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_9 <= mul_ln270_9_fu_1164_p2(29 downto 14);
        else 
            layer11_out_9 <= layer11_out_9_preg;
        end if; 
    end process;


    layer11_out_9_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            layer11_out_9_ap_vld <= ap_const_logic_1;
        else 
            layer11_out_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln270_1_fu_1004_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_1_fu_1004_p1 <= mul_ln270_1_fu_1004_p10(15 - 1 downto 0);
    mul_ln270_1_fu_1004_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_reg_1286),30));
    mul_ln270_2_fu_1024_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_2_fu_1024_p1 <= mul_ln270_2_fu_1024_p10(15 - 1 downto 0);
    mul_ln270_2_fu_1024_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_2_reg_1291),30));
    mul_ln270_3_fu_1044_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_3_fu_1044_p1 <= mul_ln270_3_fu_1044_p10(15 - 1 downto 0);
    mul_ln270_3_fu_1044_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_2_reg_1296),30));
    mul_ln270_4_fu_1064_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_4_fu_1064_p1 <= mul_ln270_4_fu_1064_p10(15 - 1 downto 0);
    mul_ln270_4_fu_1064_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_4_reg_1301),30));
    mul_ln270_5_fu_1084_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_5_fu_1084_p1 <= mul_ln270_5_fu_1084_p10(15 - 1 downto 0);
    mul_ln270_5_fu_1084_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_3_reg_1306),30));
    mul_ln270_6_fu_1104_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_6_fu_1104_p1 <= mul_ln270_6_fu_1104_p10(15 - 1 downto 0);
    mul_ln270_6_fu_1104_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_5_reg_1311),30));
    mul_ln270_7_fu_1124_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_7_fu_1124_p1 <= mul_ln270_7_fu_1124_p10(15 - 1 downto 0);
    mul_ln270_7_fu_1124_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_4_reg_1316),30));
    mul_ln270_8_fu_1144_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_8_fu_1144_p1 <= mul_ln270_8_fu_1144_p10(15 - 1 downto 0);
    mul_ln270_8_fu_1144_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_6_reg_1321),30));
    mul_ln270_9_fu_1164_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_9_fu_1164_p1 <= mul_ln270_9_fu_1164_p10(15 - 1 downto 0);
    mul_ln270_9_fu_1164_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_6_reg_1326),30));
    mul_ln270_fu_984_p0 <= sext_ln270_fu_977_p1(18 - 1 downto 0);
    mul_ln270_fu_984_p1 <= mul_ln270_fu_984_p10(15 - 1 downto 0);
    mul_ln270_fu_984_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_1281),30));
    select_ln66_1_fu_376_p3 <= 
        p_read2 when (xor_ln66_1_fu_370_p2(0) = '1') else 
        p_read3;
    select_ln66_2_fu_396_p3 <= 
        select_ln66_fu_356_p3 when (xor_ln66_2_fu_390_p2(0) = '1') else 
        select_ln66_1_fu_376_p3;
    select_ln66_3_fu_416_p3 <= 
        p_read4 when (xor_ln66_3_fu_410_p2(0) = '1') else 
        p_read5;
    select_ln66_4_fu_436_p3 <= 
        p_read6 when (xor_ln66_4_fu_430_p2(0) = '1') else 
        p_read7;
    select_ln66_5_fu_456_p3 <= 
        select_ln66_3_fu_416_p3 when (xor_ln66_5_fu_450_p2(0) = '1') else 
        select_ln66_4_fu_436_p3;
    select_ln66_8_fu_524_p3 <= 
        trunc_ln66_fu_516_p1 when (xor_ln66_8_fu_510_p2(0) = '1') else 
        trunc_ln66_1_fu_520_p1;
    select_ln66_fu_356_p3 <= 
        p_read when (xor_ln66_fu_350_p2(0) = '1') else 
        p_read1;
        sext_ln270_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table_q0),30));

    trunc_ln248_1_fu_542_p1 <= p_read1(15 - 1 downto 0);
    trunc_ln248_2_fu_552_p1 <= p_read2(15 - 1 downto 0);
    trunc_ln248_3_fu_562_p1 <= p_read3(15 - 1 downto 0);
    trunc_ln248_4_fu_572_p1 <= p_read4(15 - 1 downto 0);
    trunc_ln248_5_fu_582_p1 <= p_read5(15 - 1 downto 0);
    trunc_ln248_6_fu_592_p1 <= p_read6(15 - 1 downto 0);
    trunc_ln248_7_fu_602_p1 <= p_read7(15 - 1 downto 0);
    trunc_ln248_8_fu_612_p1 <= p_read8(15 - 1 downto 0);
    trunc_ln248_9_fu_622_p1 <= p_read9(15 - 1 downto 0);
    trunc_ln248_fu_532_p1 <= p_read(15 - 1 downto 0);
    trunc_ln66_1_fu_520_p1 <= b_1_fu_496_p3(15 - 1 downto 0);
    trunc_ln66_fu_516_p1 <= a_1_fu_476_p3(15 - 1 downto 0);
    trunc_ln_fu_962_p4 <= add_ln51_8_fu_956_p2(17 downto 12);
    xor_ln66_1_fu_370_p2 <= (icmp_ln66_1_fu_364_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_390_p2 <= (icmp_ln66_2_fu_384_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_410_p2 <= (icmp_ln66_3_fu_404_p2 xor ap_const_lv1_1);
    xor_ln66_4_fu_430_p2 <= (icmp_ln66_4_fu_424_p2 xor ap_const_lv1_1);
    xor_ln66_5_fu_450_p2 <= (icmp_ln66_5_fu_444_p2 xor ap_const_lv1_1);
    xor_ln66_6_fu_470_p2 <= (icmp_ln66_6_fu_464_p2 xor ap_const_lv1_1);
    xor_ln66_7_fu_490_p2 <= (icmp_ln66_7_fu_484_p2 xor ap_const_lv1_1);
    xor_ln66_8_fu_510_p2 <= (icmp_ln66_8_fu_504_p2 xor ap_const_lv1_1);
    xor_ln66_fu_350_p2 <= (icmp_ln66_fu_344_p2 xor ap_const_lv1_1);
    zext_ln141_1_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_fu_784_p3),16));
    zext_ln141_2_fu_804_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_2_fu_796_p3),16));
    zext_ln141_3_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_2_fu_808_p3),17));
    zext_ln141_4_fu_828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_4_fu_820_p3),16));
    zext_ln141_5_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_3_fu_832_p3),16));
    zext_ln141_6_fu_852_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_5_fu_844_p3),16));
    zext_ln141_7_fu_864_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_4_fu_856_p3),18));
    zext_ln141_8_fu_876_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_6_fu_868_p3),16));
    zext_ln141_fu_780_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_fu_772_p3),16));
    zext_ln258_1_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_1186),64));
    zext_ln258_2_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1191),64));
    zext_ln258_3_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_1196),64));
    zext_ln258_4_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_reg_1201),64));
    zext_ln258_5_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_reg_1206),64));
    zext_ln258_6_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_1211),64));
    zext_ln258_7_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_1216),64));
    zext_ln258_8_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_1221),64));
    zext_ln258_9_fu_768_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_1226),64));
    zext_ln258_fu_732_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_1181),64));
    zext_ln267_fu_972_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_fu_962_p4),64));
    zext_ln51_1_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_7_fu_898_p2),17));
    zext_ln51_2_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_7_fu_930_p2),18));
    zext_ln51_3_fu_926_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_4_fu_920_p2),17));
    zext_ln51_4_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln51_7_fu_946_p2),18));
    zext_ln51_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_6_fu_880_p3),16));
end behav;
