// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        layer11_out_0,
        layer11_out_0_ap_vld,
        layer11_out_1,
        layer11_out_1_ap_vld,
        layer11_out_2,
        layer11_out_2_ap_vld,
        layer11_out_3,
        layer11_out_3_ap_vld,
        layer11_out_4,
        layer11_out_4_ap_vld,
        layer11_out_5,
        layer11_out_5_ap_vld,
        layer11_out_6,
        layer11_out_6_ap_vld,
        layer11_out_7,
        layer11_out_7_ap_vld,
        layer11_out_8,
        layer11_out_8_ap_vld,
        layer11_out_9,
        layer11_out_9_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
output  [15:0] layer11_out_0;
output   layer11_out_0_ap_vld;
output  [15:0] layer11_out_1;
output   layer11_out_1_ap_vld;
output  [15:0] layer11_out_2;
output   layer11_out_2_ap_vld;
output  [15:0] layer11_out_3;
output   layer11_out_3_ap_vld;
output  [15:0] layer11_out_4;
output   layer11_out_4_ap_vld;
output  [15:0] layer11_out_5;
output   layer11_out_5_ap_vld;
output  [15:0] layer11_out_6;
output   layer11_out_6_ap_vld;
output  [15:0] layer11_out_7;
output   layer11_out_7_ap_vld;
output  [15:0] layer11_out_8;
output   layer11_out_8_ap_vld;
output  [15:0] layer11_out_9;
output   layer11_out_9_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] layer11_out_0;
reg layer11_out_0_ap_vld;
reg[15:0] layer11_out_1;
reg layer11_out_1_ap_vld;
reg[15:0] layer11_out_2;
reg layer11_out_2_ap_vld;
reg[15:0] layer11_out_3;
reg layer11_out_3_ap_vld;
reg[15:0] layer11_out_4;
reg layer11_out_4_ap_vld;
reg[15:0] layer11_out_5;
reg layer11_out_5_ap_vld;
reg[15:0] layer11_out_6;
reg layer11_out_6_ap_vld;
reg[15:0] layer11_out_7;
reg layer11_out_7_ap_vld;
reg[15:0] layer11_out_8;
reg layer11_out_8_ap_vld;
reg[15:0] layer11_out_9;
reg layer11_out_9_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [9:0] exp_table_address0;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
wire   [10:0] exp_table_q2;
wire   [9:0] exp_table_address3;
wire   [10:0] exp_table_q3;
wire   [9:0] exp_table_address4;
wire   [10:0] exp_table_q4;
wire   [9:0] exp_table_address5;
wire   [10:0] exp_table_q5;
wire   [9:0] exp_table_address6;
wire   [10:0] exp_table_q6;
wire   [9:0] exp_table_address7;
wire   [10:0] exp_table_q7;
wire   [9:0] exp_table_address8;
wire   [10:0] exp_table_q8;
wire   [9:0] exp_table_address9;
wire   [10:0] exp_table_q9;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg   [9:0] tmp_reg_1181;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] tmp_2_reg_1186;
reg   [9:0] tmp_4_reg_1191;
reg   [9:0] tmp_6_reg_1196;
reg   [9:0] tmp_8_reg_1201;
reg   [9:0] tmp_s_reg_1206;
reg   [9:0] tmp_1_reg_1211;
reg   [9:0] tmp_3_reg_1216;
reg   [9:0] tmp_5_reg_1221;
reg   [9:0] tmp_7_reg_1226;
wire   [14:0] a_fu_772_p3;
reg   [14:0] a_reg_1281;
wire   [14:0] b_fu_784_p3;
reg   [14:0] b_reg_1286;
wire   [14:0] a_2_fu_796_p3;
reg   [14:0] a_2_reg_1291;
wire   [14:0] b_2_fu_808_p3;
reg   [14:0] b_2_reg_1296;
wire   [14:0] a_4_fu_820_p3;
reg   [14:0] a_4_reg_1301;
wire   [14:0] b_3_fu_832_p3;
reg   [14:0] b_3_reg_1306;
wire   [14:0] a_5_fu_844_p3;
reg   [14:0] a_5_reg_1311;
wire   [14:0] b_4_fu_856_p3;
reg   [14:0] b_4_reg_1316;
wire   [14:0] a_6_fu_868_p3;
reg   [14:0] a_6_reg_1321;
wire   [14:0] b_6_fu_880_p3;
reg   [14:0] b_6_reg_1326;
wire   [63:0] zext_ln258_fu_732_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln258_1_fu_736_p1;
wire   [63:0] zext_ln258_2_fu_740_p1;
wire   [63:0] zext_ln258_3_fu_744_p1;
wire   [63:0] zext_ln258_4_fu_748_p1;
wire   [63:0] zext_ln258_5_fu_752_p1;
wire   [63:0] zext_ln258_6_fu_756_p1;
wire   [63:0] zext_ln258_7_fu_760_p1;
wire   [63:0] zext_ln258_8_fu_764_p1;
wire   [63:0] zext_ln258_9_fu_768_p1;
wire   [63:0] zext_ln267_fu_972_p1;
reg   [15:0] layer11_out_0_preg;
reg    ap_block_pp0_stage0_01001;
reg   [15:0] layer11_out_1_preg;
reg   [15:0] layer11_out_2_preg;
reg   [15:0] layer11_out_3_preg;
reg   [15:0] layer11_out_4_preg;
reg   [15:0] layer11_out_5_preg;
reg   [15:0] layer11_out_6_preg;
reg   [15:0] layer11_out_7_preg;
reg   [15:0] layer11_out_8_preg;
reg   [15:0] layer11_out_9_preg;
reg    exp_table_ce9_local;
reg    exp_table_ce8_local;
reg    exp_table_ce7_local;
reg    exp_table_ce6_local;
reg    exp_table_ce5_local;
reg    exp_table_ce4_local;
reg    exp_table_ce3_local;
reg    exp_table_ce2_local;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg    invert_table_ce0_local;
wire   [0:0] icmp_ln66_fu_344_p2;
wire   [0:0] xor_ln66_fu_350_p2;
wire   [0:0] icmp_ln66_1_fu_364_p2;
wire   [0:0] xor_ln66_1_fu_370_p2;
wire   [15:0] select_ln66_fu_356_p3;
wire   [15:0] select_ln66_1_fu_376_p3;
wire   [0:0] icmp_ln66_2_fu_384_p2;
wire   [0:0] xor_ln66_2_fu_390_p2;
wire   [0:0] icmp_ln66_3_fu_404_p2;
wire   [0:0] xor_ln66_3_fu_410_p2;
wire   [0:0] icmp_ln66_4_fu_424_p2;
wire   [0:0] xor_ln66_4_fu_430_p2;
wire   [15:0] select_ln66_3_fu_416_p3;
wire   [15:0] select_ln66_4_fu_436_p3;
wire   [0:0] icmp_ln66_5_fu_444_p2;
wire   [0:0] xor_ln66_5_fu_450_p2;
wire   [15:0] select_ln66_2_fu_396_p3;
wire   [15:0] select_ln66_5_fu_456_p3;
wire   [0:0] icmp_ln66_6_fu_464_p2;
wire   [0:0] xor_ln66_6_fu_470_p2;
wire   [0:0] icmp_ln66_7_fu_484_p2;
wire   [0:0] xor_ln66_7_fu_490_p2;
wire   [15:0] a_1_fu_476_p3;
wire   [15:0] b_1_fu_496_p3;
wire   [0:0] icmp_ln66_8_fu_504_p2;
wire   [0:0] xor_ln66_8_fu_510_p2;
wire   [14:0] trunc_ln66_fu_516_p1;
wire   [14:0] trunc_ln66_1_fu_520_p1;
wire   [14:0] select_ln66_8_fu_524_p3;
wire   [14:0] trunc_ln248_fu_532_p1;
wire   [14:0] trunc_ln248_1_fu_542_p1;
wire   [14:0] trunc_ln248_2_fu_552_p1;
wire   [14:0] trunc_ln248_3_fu_562_p1;
wire   [14:0] trunc_ln248_4_fu_572_p1;
wire   [14:0] trunc_ln248_5_fu_582_p1;
wire   [14:0] trunc_ln248_6_fu_592_p1;
wire   [14:0] trunc_ln248_7_fu_602_p1;
wire   [14:0] trunc_ln248_8_fu_612_p1;
wire   [14:0] trunc_ln248_9_fu_622_p1;
wire   [14:0] d_xi_xmax_fu_536_p2;
wire   [14:0] d_xi_xmax_10_fu_546_p2;
wire   [14:0] d_xi_xmax_11_fu_556_p2;
wire   [14:0] d_xi_xmax_12_fu_566_p2;
wire   [14:0] d_xi_xmax_13_fu_576_p2;
wire   [14:0] d_xi_xmax_14_fu_586_p2;
wire   [14:0] d_xi_xmax_15_fu_596_p2;
wire   [14:0] d_xi_xmax_16_fu_606_p2;
wire   [14:0] d_xi_xmax_17_fu_616_p2;
wire   [14:0] d_xi_xmax_18_fu_626_p2;
wire   [15:0] zext_ln141_fu_780_p1;
wire   [15:0] zext_ln141_2_fu_804_p1;
wire   [15:0] add_ln51_fu_892_p2;
wire   [15:0] zext_ln141_1_fu_792_p1;
wire   [15:0] a_7_fu_898_p2;
wire   [16:0] zext_ln51_1_fu_904_p1;
wire   [16:0] zext_ln141_3_fu_816_p1;
wire   [15:0] zext_ln141_5_fu_840_p1;
wire   [15:0] zext_ln141_6_fu_852_p1;
wire   [15:0] add_ln51_3_fu_914_p2;
wire   [15:0] zext_ln141_4_fu_828_p1;
wire   [15:0] add_ln51_4_fu_920_p2;
wire   [16:0] zext_ln51_3_fu_926_p1;
wire   [16:0] add_ln51_2_fu_908_p2;
wire   [16:0] b_7_fu_930_p2;
wire   [17:0] zext_ln51_2_fu_936_p1;
wire   [17:0] zext_ln141_7_fu_864_p1;
wire   [15:0] zext_ln141_8_fu_876_p1;
wire   [15:0] zext_ln51_fu_888_p1;
wire   [15:0] add_ln51_7_fu_946_p2;
wire   [17:0] zext_ln51_4_fu_952_p1;
wire   [17:0] add_ln51_6_fu_940_p2;
wire   [17:0] add_ln51_8_fu_956_p2;
wire   [5:0] trunc_ln_fu_962_p4;
wire  signed [17:0] mul_ln270_fu_984_p0;
wire  signed [29:0] sext_ln270_fu_977_p1;
wire   [14:0] mul_ln270_fu_984_p1;
wire   [29:0] mul_ln270_fu_984_p2;
wire  signed [17:0] mul_ln270_1_fu_1004_p0;
wire   [14:0] mul_ln270_1_fu_1004_p1;
wire   [29:0] mul_ln270_1_fu_1004_p2;
wire  signed [17:0] mul_ln270_2_fu_1024_p0;
wire   [14:0] mul_ln270_2_fu_1024_p1;
wire   [29:0] mul_ln270_2_fu_1024_p2;
wire  signed [17:0] mul_ln270_3_fu_1044_p0;
wire   [14:0] mul_ln270_3_fu_1044_p1;
wire   [29:0] mul_ln270_3_fu_1044_p2;
wire  signed [17:0] mul_ln270_4_fu_1064_p0;
wire   [14:0] mul_ln270_4_fu_1064_p1;
wire   [29:0] mul_ln270_4_fu_1064_p2;
wire  signed [17:0] mul_ln270_5_fu_1084_p0;
wire   [14:0] mul_ln270_5_fu_1084_p1;
wire   [29:0] mul_ln270_5_fu_1084_p2;
wire  signed [17:0] mul_ln270_6_fu_1104_p0;
wire   [14:0] mul_ln270_6_fu_1104_p1;
wire   [29:0] mul_ln270_6_fu_1104_p2;
wire  signed [17:0] mul_ln270_7_fu_1124_p0;
wire   [14:0] mul_ln270_7_fu_1124_p1;
wire   [29:0] mul_ln270_7_fu_1124_p2;
wire  signed [17:0] mul_ln270_8_fu_1144_p0;
wire   [14:0] mul_ln270_8_fu_1144_p1;
wire   [29:0] mul_ln270_8_fu_1144_p2;
wire  signed [17:0] mul_ln270_9_fu_1164_p0;
wire   [14:0] mul_ln270_9_fu_1164_p1;
wire   [29:0] mul_ln270_9_fu_1164_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_init_pp0;
wire    ap_enable_pp0;
wire   [29:0] mul_ln270_1_fu_1004_p10;
wire   [29:0] mul_ln270_2_fu_1024_p10;
wire   [29:0] mul_ln270_3_fu_1044_p10;
wire   [29:0] mul_ln270_4_fu_1064_p10;
wire   [29:0] mul_ln270_5_fu_1084_p10;
wire   [29:0] mul_ln270_6_fu_1104_p10;
wire   [29:0] mul_ln270_7_fu_1124_p10;
wire   [29:0] mul_ln270_8_fu_1144_p10;
wire   [29:0] mul_ln270_9_fu_1164_p10;
wire   [29:0] mul_ln270_fu_984_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 layer11_out_0_preg = 16'd0;
#0 layer11_out_1_preg = 16'd0;
#0 layer11_out_2_preg = 16'd0;
#0 layer11_out_3_preg = 16'd0;
#0 layer11_out_4_preg = 16'd0;
#0 layer11_out_5_preg = 16'd0;
#0 layer11_out_6_preg = 16'd0;
#0 layer11_out_7_preg = 16'd0;
#0 layer11_out_8_preg = 16'd0;
#0 layer11_out_9_preg = 16'd0;
end

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_exp_table_ROM_g8j #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0_local),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2_local),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3_local),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4_local),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5_local),
    .q5(exp_table_q5),
    .address6(exp_table_address6),
    .ce6(exp_table_ce6_local),
    .q6(exp_table_q6),
    .address7(exp_table_address7),
    .ce7(exp_table_ce7_local),
    .q7(exp_table_q7),
    .address8(exp_table_address8),
    .ce8(exp_table_ce8_local),
    .q8(exp_table_q8),
    .address9(exp_table_address9),
    .ce9(exp_table_ce9_local),
    .q9(exp_table_q9)
);

myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s_invert_table_Rhbi #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11834(
    .din0(mul_ln270_fu_984_p0),
    .din1(mul_ln270_fu_984_p1),
    .dout(mul_ln270_fu_984_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11835(
    .din0(mul_ln270_1_fu_1004_p0),
    .din1(mul_ln270_1_fu_1004_p1),
    .dout(mul_ln270_1_fu_1004_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11836(
    .din0(mul_ln270_2_fu_1024_p0),
    .din1(mul_ln270_2_fu_1024_p1),
    .dout(mul_ln270_2_fu_1024_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11837(
    .din0(mul_ln270_3_fu_1044_p0),
    .din1(mul_ln270_3_fu_1044_p1),
    .dout(mul_ln270_3_fu_1044_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11838(
    .din0(mul_ln270_4_fu_1064_p0),
    .din1(mul_ln270_4_fu_1064_p1),
    .dout(mul_ln270_4_fu_1064_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11839(
    .din0(mul_ln270_5_fu_1084_p0),
    .din1(mul_ln270_5_fu_1084_p1),
    .dout(mul_ln270_5_fu_1084_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11840(
    .din0(mul_ln270_6_fu_1104_p0),
    .din1(mul_ln270_6_fu_1104_p1),
    .dout(mul_ln270_6_fu_1104_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11841(
    .din0(mul_ln270_7_fu_1124_p0),
    .din1(mul_ln270_7_fu_1124_p1),
    .dout(mul_ln270_7_fu_1124_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11842(
    .din0(mul_ln270_8_fu_1144_p0),
    .din1(mul_ln270_8_fu_1144_p1),
    .dout(mul_ln270_8_fu_1144_p2)
);

myproject_mul_18s_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_18s_15ns_30_1_1_U11843(
    .din0(mul_ln270_9_fu_1164_p0),
    .din1(mul_ln270_9_fu_1164_p1),
    .dout(mul_ln270_9_fu_1164_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_0_preg <= {{mul_ln270_fu_984_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_1_preg <= {{mul_ln270_1_fu_1004_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_2_preg <= {{mul_ln270_2_fu_1024_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_3_preg <= {{mul_ln270_3_fu_1044_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_4_preg <= {{mul_ln270_4_fu_1064_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_5_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_5_preg <= {{mul_ln270_5_fu_1084_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_6_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_6_preg <= {{mul_ln270_6_fu_1104_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_7_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_7_preg <= {{mul_ln270_7_fu_1124_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_8_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_8_preg <= {{mul_ln270_8_fu_1144_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        layer11_out_9_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            layer11_out_9_preg <= {{mul_ln270_9_fu_1164_p2[29:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_2_reg_1291[14 : 4] <= a_2_fu_796_p3[14 : 4];
        a_4_reg_1301[14 : 4] <= a_4_fu_820_p3[14 : 4];
        a_5_reg_1311[14 : 4] <= a_5_fu_844_p3[14 : 4];
        a_6_reg_1321[14 : 4] <= a_6_fu_868_p3[14 : 4];
        a_reg_1281[14 : 4] <= a_fu_772_p3[14 : 4];
        b_2_reg_1296[14 : 4] <= b_2_fu_808_p3[14 : 4];
        b_3_reg_1306[14 : 4] <= b_3_fu_832_p3[14 : 4];
        b_4_reg_1316[14 : 4] <= b_4_fu_856_p3[14 : 4];
        b_6_reg_1326[14 : 4] <= b_6_fu_880_p3[14 : 4];
        b_reg_1286[14 : 4] <= b_fu_784_p3[14 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_reg_1211 <= {{d_xi_xmax_15_fu_596_p2[14:5]}};
        tmp_2_reg_1186 <= {{d_xi_xmax_10_fu_546_p2[14:5]}};
        tmp_3_reg_1216 <= {{d_xi_xmax_16_fu_606_p2[14:5]}};
        tmp_4_reg_1191 <= {{d_xi_xmax_11_fu_556_p2[14:5]}};
        tmp_5_reg_1221 <= {{d_xi_xmax_17_fu_616_p2[14:5]}};
        tmp_6_reg_1196 <= {{d_xi_xmax_12_fu_566_p2[14:5]}};
        tmp_7_reg_1226 <= {{d_xi_xmax_18_fu_626_p2[14:5]}};
        tmp_8_reg_1201 <= {{d_xi_xmax_13_fu_576_p2[14:5]}};
        tmp_reg_1181 <= {{d_xi_xmax_fu_536_p2[14:5]}};
        tmp_s_reg_1206 <= {{d_xi_xmax_14_fu_586_p2[14:5]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to2 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce2_local = 1'b1;
    end else begin
        exp_table_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce3_local = 1'b1;
    end else begin
        exp_table_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce4_local = 1'b1;
    end else begin
        exp_table_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce5_local = 1'b1;
    end else begin
        exp_table_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce6_local = 1'b1;
    end else begin
        exp_table_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce7_local = 1'b1;
    end else begin
        exp_table_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce8_local = 1'b1;
    end else begin
        exp_table_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce9_local = 1'b1;
    end else begin
        exp_table_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_0 = {{mul_ln270_fu_984_p2[29:14]}};
    end else begin
        layer11_out_0 = layer11_out_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_0_ap_vld = 1'b1;
    end else begin
        layer11_out_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_1 = {{mul_ln270_1_fu_1004_p2[29:14]}};
    end else begin
        layer11_out_1 = layer11_out_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_1_ap_vld = 1'b1;
    end else begin
        layer11_out_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_2 = {{mul_ln270_2_fu_1024_p2[29:14]}};
    end else begin
        layer11_out_2 = layer11_out_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_2_ap_vld = 1'b1;
    end else begin
        layer11_out_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_3 = {{mul_ln270_3_fu_1044_p2[29:14]}};
    end else begin
        layer11_out_3 = layer11_out_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_3_ap_vld = 1'b1;
    end else begin
        layer11_out_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_4 = {{mul_ln270_4_fu_1064_p2[29:14]}};
    end else begin
        layer11_out_4 = layer11_out_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_4_ap_vld = 1'b1;
    end else begin
        layer11_out_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_5 = {{mul_ln270_5_fu_1084_p2[29:14]}};
    end else begin
        layer11_out_5 = layer11_out_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_5_ap_vld = 1'b1;
    end else begin
        layer11_out_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_6 = {{mul_ln270_6_fu_1104_p2[29:14]}};
    end else begin
        layer11_out_6 = layer11_out_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_6_ap_vld = 1'b1;
    end else begin
        layer11_out_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_7 = {{mul_ln270_7_fu_1124_p2[29:14]}};
    end else begin
        layer11_out_7 = layer11_out_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_7_ap_vld = 1'b1;
    end else begin
        layer11_out_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_8 = {{mul_ln270_8_fu_1144_p2[29:14]}};
    end else begin
        layer11_out_8 = layer11_out_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_8_ap_vld = 1'b1;
    end else begin
        layer11_out_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_9 = {{mul_ln270_9_fu_1164_p2[29:14]}};
    end else begin
        layer11_out_9 = layer11_out_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer11_out_9_ap_vld = 1'b1;
    end else begin
        layer11_out_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_1_fu_476_p3 = ((xor_ln66_6_fu_470_p2[0:0] == 1'b1) ? select_ln66_2_fu_396_p3 : select_ln66_5_fu_456_p3);

assign a_2_fu_796_p3 = {{exp_table_q7}, {4'd0}};

assign a_4_fu_820_p3 = {{exp_table_q5}, {4'd0}};

assign a_5_fu_844_p3 = {{exp_table_q3}, {4'd0}};

assign a_6_fu_868_p3 = {{exp_table_q1}, {4'd0}};

assign a_7_fu_898_p2 = (add_ln51_fu_892_p2 + zext_ln141_1_fu_792_p1);

assign a_fu_772_p3 = {{exp_table_q9}, {4'd0}};

assign add_ln51_2_fu_908_p2 = (zext_ln51_1_fu_904_p1 + zext_ln141_3_fu_816_p1);

assign add_ln51_3_fu_914_p2 = (zext_ln141_5_fu_840_p1 + zext_ln141_6_fu_852_p1);

assign add_ln51_4_fu_920_p2 = (add_ln51_3_fu_914_p2 + zext_ln141_4_fu_828_p1);

assign add_ln51_6_fu_940_p2 = (zext_ln51_2_fu_936_p1 + zext_ln141_7_fu_864_p1);

assign add_ln51_7_fu_946_p2 = (zext_ln141_8_fu_876_p1 + zext_ln51_fu_888_p1);

assign add_ln51_8_fu_956_p2 = (zext_ln51_4_fu_952_p1 + add_ln51_6_fu_940_p2);

assign add_ln51_fu_892_p2 = (zext_ln141_fu_780_p1 + zext_ln141_2_fu_804_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign b_1_fu_496_p3 = ((xor_ln66_7_fu_490_p2[0:0] == 1'b1) ? p_read8 : p_read9);

assign b_2_fu_808_p3 = {{exp_table_q6}, {4'd0}};

assign b_3_fu_832_p3 = {{exp_table_q4}, {4'd0}};

assign b_4_fu_856_p3 = {{exp_table_q2}, {4'd0}};

assign b_6_fu_880_p3 = {{exp_table_q0}, {4'd0}};

assign b_7_fu_930_p2 = (zext_ln51_3_fu_926_p1 + add_ln51_2_fu_908_p2);

assign b_fu_784_p3 = {{exp_table_q8}, {4'd0}};

assign d_xi_xmax_10_fu_546_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_1_fu_542_p1);

assign d_xi_xmax_11_fu_556_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_2_fu_552_p1);

assign d_xi_xmax_12_fu_566_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_3_fu_562_p1);

assign d_xi_xmax_13_fu_576_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_4_fu_572_p1);

assign d_xi_xmax_14_fu_586_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_5_fu_582_p1);

assign d_xi_xmax_15_fu_596_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_6_fu_592_p1);

assign d_xi_xmax_16_fu_606_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_7_fu_602_p1);

assign d_xi_xmax_17_fu_616_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_8_fu_612_p1);

assign d_xi_xmax_18_fu_626_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_9_fu_622_p1);

assign d_xi_xmax_fu_536_p2 = (select_ln66_8_fu_524_p3 - trunc_ln248_fu_532_p1);

assign exp_table_address0 = zext_ln258_9_fu_768_p1;

assign exp_table_address1 = zext_ln258_8_fu_764_p1;

assign exp_table_address2 = zext_ln258_7_fu_760_p1;

assign exp_table_address3 = zext_ln258_6_fu_756_p1;

assign exp_table_address4 = zext_ln258_5_fu_752_p1;

assign exp_table_address5 = zext_ln258_4_fu_748_p1;

assign exp_table_address6 = zext_ln258_3_fu_744_p1;

assign exp_table_address7 = zext_ln258_2_fu_740_p1;

assign exp_table_address8 = zext_ln258_1_fu_736_p1;

assign exp_table_address9 = zext_ln258_fu_732_p1;

assign icmp_ln66_1_fu_364_p2 = (($signed(p_read2) < $signed(p_read3)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_384_p2 = (($signed(select_ln66_fu_356_p3) < $signed(select_ln66_1_fu_376_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_404_p2 = (($signed(p_read4) < $signed(p_read5)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_424_p2 = (($signed(p_read6) < $signed(p_read7)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_444_p2 = (($signed(select_ln66_3_fu_416_p3) < $signed(select_ln66_4_fu_436_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_464_p2 = (($signed(select_ln66_2_fu_396_p3) < $signed(select_ln66_5_fu_456_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_484_p2 = (($signed(p_read8) < $signed(p_read9)) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_504_p2 = (($signed(a_1_fu_476_p3) < $signed(b_1_fu_496_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_344_p2 = (($signed(p_read) < $signed(p_read1)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln267_fu_972_p1;

assign mul_ln270_1_fu_1004_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_1_fu_1004_p1 = mul_ln270_1_fu_1004_p10;

assign mul_ln270_1_fu_1004_p10 = b_reg_1286;

assign mul_ln270_2_fu_1024_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_2_fu_1024_p1 = mul_ln270_2_fu_1024_p10;

assign mul_ln270_2_fu_1024_p10 = a_2_reg_1291;

assign mul_ln270_3_fu_1044_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_3_fu_1044_p1 = mul_ln270_3_fu_1044_p10;

assign mul_ln270_3_fu_1044_p10 = b_2_reg_1296;

assign mul_ln270_4_fu_1064_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_4_fu_1064_p1 = mul_ln270_4_fu_1064_p10;

assign mul_ln270_4_fu_1064_p10 = a_4_reg_1301;

assign mul_ln270_5_fu_1084_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_5_fu_1084_p1 = mul_ln270_5_fu_1084_p10;

assign mul_ln270_5_fu_1084_p10 = b_3_reg_1306;

assign mul_ln270_6_fu_1104_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_6_fu_1104_p1 = mul_ln270_6_fu_1104_p10;

assign mul_ln270_6_fu_1104_p10 = a_5_reg_1311;

assign mul_ln270_7_fu_1124_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_7_fu_1124_p1 = mul_ln270_7_fu_1124_p10;

assign mul_ln270_7_fu_1124_p10 = b_4_reg_1316;

assign mul_ln270_8_fu_1144_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_8_fu_1144_p1 = mul_ln270_8_fu_1144_p10;

assign mul_ln270_8_fu_1144_p10 = a_6_reg_1321;

assign mul_ln270_9_fu_1164_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_9_fu_1164_p1 = mul_ln270_9_fu_1164_p10;

assign mul_ln270_9_fu_1164_p10 = b_6_reg_1326;

assign mul_ln270_fu_984_p0 = sext_ln270_fu_977_p1;

assign mul_ln270_fu_984_p1 = mul_ln270_fu_984_p10;

assign mul_ln270_fu_984_p10 = a_reg_1281;

assign select_ln66_1_fu_376_p3 = ((xor_ln66_1_fu_370_p2[0:0] == 1'b1) ? p_read2 : p_read3);

assign select_ln66_2_fu_396_p3 = ((xor_ln66_2_fu_390_p2[0:0] == 1'b1) ? select_ln66_fu_356_p3 : select_ln66_1_fu_376_p3);

assign select_ln66_3_fu_416_p3 = ((xor_ln66_3_fu_410_p2[0:0] == 1'b1) ? p_read4 : p_read5);

assign select_ln66_4_fu_436_p3 = ((xor_ln66_4_fu_430_p2[0:0] == 1'b1) ? p_read6 : p_read7);

assign select_ln66_5_fu_456_p3 = ((xor_ln66_5_fu_450_p2[0:0] == 1'b1) ? select_ln66_3_fu_416_p3 : select_ln66_4_fu_436_p3);

assign select_ln66_8_fu_524_p3 = ((xor_ln66_8_fu_510_p2[0:0] == 1'b1) ? trunc_ln66_fu_516_p1 : trunc_ln66_1_fu_520_p1);

assign select_ln66_fu_356_p3 = ((xor_ln66_fu_350_p2[0:0] == 1'b1) ? p_read : p_read1);

assign sext_ln270_fu_977_p1 = $signed(invert_table_q0);

assign trunc_ln248_1_fu_542_p1 = p_read1[14:0];

assign trunc_ln248_2_fu_552_p1 = p_read2[14:0];

assign trunc_ln248_3_fu_562_p1 = p_read3[14:0];

assign trunc_ln248_4_fu_572_p1 = p_read4[14:0];

assign trunc_ln248_5_fu_582_p1 = p_read5[14:0];

assign trunc_ln248_6_fu_592_p1 = p_read6[14:0];

assign trunc_ln248_7_fu_602_p1 = p_read7[14:0];

assign trunc_ln248_8_fu_612_p1 = p_read8[14:0];

assign trunc_ln248_9_fu_622_p1 = p_read9[14:0];

assign trunc_ln248_fu_532_p1 = p_read[14:0];

assign trunc_ln66_1_fu_520_p1 = b_1_fu_496_p3[14:0];

assign trunc_ln66_fu_516_p1 = a_1_fu_476_p3[14:0];

assign trunc_ln_fu_962_p4 = {{add_ln51_8_fu_956_p2[17:12]}};

assign xor_ln66_1_fu_370_p2 = (icmp_ln66_1_fu_364_p2 ^ 1'd1);

assign xor_ln66_2_fu_390_p2 = (icmp_ln66_2_fu_384_p2 ^ 1'd1);

assign xor_ln66_3_fu_410_p2 = (icmp_ln66_3_fu_404_p2 ^ 1'd1);

assign xor_ln66_4_fu_430_p2 = (icmp_ln66_4_fu_424_p2 ^ 1'd1);

assign xor_ln66_5_fu_450_p2 = (icmp_ln66_5_fu_444_p2 ^ 1'd1);

assign xor_ln66_6_fu_470_p2 = (icmp_ln66_6_fu_464_p2 ^ 1'd1);

assign xor_ln66_7_fu_490_p2 = (icmp_ln66_7_fu_484_p2 ^ 1'd1);

assign xor_ln66_8_fu_510_p2 = (icmp_ln66_8_fu_504_p2 ^ 1'd1);

assign xor_ln66_fu_350_p2 = (icmp_ln66_fu_344_p2 ^ 1'd1);

assign zext_ln141_1_fu_792_p1 = b_fu_784_p3;

assign zext_ln141_2_fu_804_p1 = a_2_fu_796_p3;

assign zext_ln141_3_fu_816_p1 = b_2_fu_808_p3;

assign zext_ln141_4_fu_828_p1 = a_4_fu_820_p3;

assign zext_ln141_5_fu_840_p1 = b_3_fu_832_p3;

assign zext_ln141_6_fu_852_p1 = a_5_fu_844_p3;

assign zext_ln141_7_fu_864_p1 = b_4_fu_856_p3;

assign zext_ln141_8_fu_876_p1 = a_6_fu_868_p3;

assign zext_ln141_fu_780_p1 = a_fu_772_p3;

assign zext_ln258_1_fu_736_p1 = tmp_2_reg_1186;

assign zext_ln258_2_fu_740_p1 = tmp_4_reg_1191;

assign zext_ln258_3_fu_744_p1 = tmp_6_reg_1196;

assign zext_ln258_4_fu_748_p1 = tmp_8_reg_1201;

assign zext_ln258_5_fu_752_p1 = tmp_s_reg_1206;

assign zext_ln258_6_fu_756_p1 = tmp_1_reg_1211;

assign zext_ln258_7_fu_760_p1 = tmp_3_reg_1216;

assign zext_ln258_8_fu_764_p1 = tmp_5_reg_1221;

assign zext_ln258_9_fu_768_p1 = tmp_7_reg_1226;

assign zext_ln258_fu_732_p1 = tmp_reg_1181;

assign zext_ln267_fu_972_p1 = trunc_ln_fu_962_p4;

assign zext_ln51_1_fu_904_p1 = a_7_fu_898_p2;

assign zext_ln51_2_fu_936_p1 = b_7_fu_930_p2;

assign zext_ln51_3_fu_926_p1 = add_ln51_4_fu_920_p2;

assign zext_ln51_4_fu_952_p1 = add_ln51_7_fu_946_p2;

assign zext_ln51_fu_888_p1 = b_6_fu_880_p3;

always @ (posedge ap_clk) begin
    a_reg_1281[3:0] <= 4'b0000;
    b_reg_1286[3:0] <= 4'b0000;
    a_2_reg_1291[3:0] <= 4'b0000;
    b_2_reg_1296[3:0] <= 4'b0000;
    a_4_reg_1301[3:0] <= 4'b0000;
    b_3_reg_1306[3:0] <= 4'b0000;
    a_5_reg_1311[3:0] <= 4'b0000;
    b_4_reg_1316[3:0] <= 4'b0000;
    a_6_reg_1321[3:0] <= 4'b0000;
    b_6_reg_1326[3:0] <= 4'b0000;
end

endmodule //myproject_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config11_s
