// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module myproject_partselect_16ns_12544ns_12ns_16_1_1 (sel,din,dout);

parameter ADDRWIDTH = 12;
parameter DATAWIDTH = 12544;
parameter DATA1WIDTH = 16;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
output [DATA1WIDTH-1:0] dout;

wire [DATAWIDTH+DATA1WIDTH-1:0] din_tmp;
wire [DATA1WIDTH-1:0] dout_tmp;




assign din_tmp = { 16'b0000000000000000,din };

assign dout_tmp = din_tmp[sel+16-1 -: 16];




assign dout = dout_tmp;




endmodule
